### ISSUE TITLE
Build errors in unrelated tsx files

### ISSUE THREAD

**Issue by hisuwh** [victorgarciaesgi/vue-chart-3#47]
I'm unable to upgrade from vue-chart-3@0.4.8 to latest v0.5.11 as I am getting build errors in my Vue TSX files that are not using charts:

 ```
TS2322: Type '{ src: string; width: string; height: string; border: string; }' is not assignable to type 'ElementAttrs<IframeHTMLAttributes>'.
  Property 'border' does not exist on type 'ElementAttrs<IframeHTMLAttributes>'.
    42 |                                 width="100%"
    43 |                                 height="800px"
  > 44 |                                 border="none"
       |                                 ^^^^^^
    45 |                             >
    46 |                             </iframe>
    47 |                         )}
```

I notice you have taken a dependency on `@vue/runtime-core` and `@vue/runtime-dom`  v3.2.20 (https://github.com/victorgarciaesgi/vue-chart-3/blob/main/package.json#L54) - I wonder if this could be a factor?

**Comment by victorgarciaesgi** [comment]
Hum that's weird. Do you use the JSX shim?  I think a will release a version specifically for Vue 3 and another for Vue 2. It becomes too complicated to manage dependencies and types with only `vue-demi`. I will keep a branch updated for Vue 2

**Comment by hisuwh** [comment]
I've been going through the versions and it looks like `v0.4.10` is when it started breaking.  Which looks like when you introduced the dependency on `@vue/runtime-core` and `@vue/runtime-dom`: https://github.com/victorgarciaesgi/vue-chart-3/compare/v0.4.8...v0.4.10

**Comment by maiolica** [comment]
I'm having a similar issue, downgrading to v0.4.8 fixes this, thanks @hisuwh for the hint.

**Comment by victorgarciaesgi** [comment]
Sorry for the lack of updates, I don't have much time recently to work on it. Will keep you updated

**Comment by victorgarciaesgi** [comment]
@hisuwh  @maiolica  New version only for Vue 3 is out. With a legacy 2.x for Vue 2! Check out the new docs :)

**Comment by victorgarciaesgi** [comment]
Tell me if that fixes your problem

**Comment by maiolica** [comment]
Hi Victor, it seems to be working great, thank you for your work on the docs too!

**Comment by hisuwh** [comment]
I'm getting a new error now:
```
 Property 'class' does not exist on type 'Readonly<Partial<{ height: number; width: number; plugins: Plugin<keyof ChartTypeRegistry, AnyObject>[]; chartId: string; cssClasses: string; }> & Omit<...>>'.
    25 |         return (
    26 |             <Doughnut
  > 27 |                 class="position-relative h-100"
       |                 ^^^^^
    28 |                 chartData={chartData}
    29 |                 options={chartOptions}
    30 |             />
```

**Comment by victorgarciaesgi** [comment]
@hisuwh Volar is returning this error? I'll check if htmlAttrs is declared

**Comment by victorgarciaesgi** [comment]
Oh it's on tsx render function sorry

**Comment by victorgarciaesgi** [comment]
Hmm no error on my side
![image](https://user-images.githubusercontent.com/15092120/143072091-5e901035-6d63-49a5-9533-ef87e248ef6c.png)

**Comment by victorgarciaesgi** [comment]
Oh ok it's the build step that fails. Weird

**Comment by hisuwh** [comment]
What if you assign the props explicitly rather than spread?

**Comment by hisuwh** [comment]
I get the error on build and in Vs code

**Comment by victorgarciaesgi** [comment]
I know where it comes from. I use the type `ExtractPropTypes` and it's not made for tsx. I will fix it tonight

**Comment by victorgarciaesgi** [comment]
@hisuwh Should be fixed on `3.0.1`

**Comment by hisuwh** [comment]
3.0.1? I'm using Vue 2. Is that right?

**Comment by victorgarciaesgi** [comment]
Oh shit I though you were on Vue 3 aha

**Comment by hisuwh** [comment]
My bad tbf - I never specified

**Comment by victorgarciaesgi** [comment]
@hisuwh Try `2.0.2` it should work now

**Comment by hisuwh** [comment]
Mmm same problem. 
![image](https://user-images.githubusercontent.com/4470351/143473984-8f32828f-afea-4d8b-8f4c-b994d184877c.png)

**Comment by jedy05097952** [comment]
I'm having a similar error in Vue3 version
It's only worked on 0.4.8

```
ERROR in src/views/transaction-management/withdraw-review/index.vue:382:19
TS2339: Property '$t' does not exist on type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>'.
    380 |       const fileName = `${dayjs(param[`${conditions.dateType}_at_before`]).format(
    381 |         'YYYYMMDD'
  > 382 |       )}-${proxy?.$t('menu.withdraw_review')}.csv`
        |                   ^^
    383 |       downloadFile('/manage/report/withdraw/', fileName, param)
    384 |     }
    385 |
```

**Comment by victorgarciaesgi** [comment]
@hisuwh sorry i don't have much time lately i will look into it

**Comment by victorgarciaesgi** [comment]
> I'm having a similar error in Vue3 version
> 
> it's worked on 0.4.8
> 
> 
> 
> ```
> 
> ERROR in src/views/transaction-management/withdraw-review/index.vue:382:19
> 
> TS2339: Property '$t' does not exist on type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>'.
> 
>     380 |       const fileName = `${dayjs(param[`${conditions.dateType}_at_before`]).format(
> 
>     381 |         'YYYYMMDD'
> 
>   > 382 |       )}-${proxy?.$t('menu.withdraw_review')}.csv`
> 
>         |                   ^^
> 
>     383 |       downloadFile('/manage/report/withdraw/', fileName, param)
> 
>     384 |     }
> 
>     385 |
> 
> ```

This error is not related to vue-chart-3

**Comment by victorgarciaesgi** [comment]
@hisuwh Still have the problem?

**Comment by hisuwh** [comment]
@victorgarciaesgi upgraded to 2.0.3 and yes it seems I still have the same problem:
![image](https://user-images.githubusercontent.com/4470351/148038226-ccbaf4f4-423e-488f-91e1-9f3222937111.png)

**Comment by hisuwh** [comment]
@victorgarciaesgi any more guidance on this?

**Comment by victorgarciaesgi** [comment]
I will look at it. It's really strange because the error only shows in the cli on the on the IDE

**Comment by hisuwh** [comment]
@victorgarciaesgi this might help - at least I can update for new features?
