### ISSUE TITLE
[0.3.2] Cannot find module '@vue/runtime-dom' or its corresponding type declarations.

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [victorgarciaesgi/vue-chart-3#10]
Thanks for the package, works great so far except the following typescript error. I'm using Vue 2 with VCA plugin, so there's no `@vue/runtime-dom` package installed obviously. The error itself is gone after I've installed it but there are other JSX related errors, so probably not the way to go

```
ERROR in .../node_modules/vue-chart-3/types/components.d.ts(3,36):
3:36 Cannot find module '@vue/runtime-dom' or its corresponding type declarations.
    1 | import { Chart, ChartData, Plugin } from 'chart.js';
    2 | import { PropType } from 'vue-demi';
  > 3 | import type { CSSProperties } from '@vue/runtime-dom';
      |                                    ^
```

EDIT: `"skipLibCheck": true` seems to do the job as well, the question remains though - is this the correct solution?

**Comment by victorgarciaesgi** [comment]
Hmm that's maybe because I didn't put in the the resolutions! I will fix it thanks for the report @jacekkarczmarczyk ! :)

**Comment by victorgarciaesgi** [comment]
Should be fixed on 0.3.4!

**Comment by jacekkarczmarczyk** [comment]
Hmmm, I'm still having the same error in 0.3.4

**Comment by victorgarciaesgi** [comment]
Try reinstalling your dependencies `yarn` or `npm i`, or delete node_modules and reinstall. I changed the peerDependencies

**Comment by jacekkarczmarczyk** [comment]
```
rm node_modules/ -rf
yarn cache clean
yarn
yarn build
```
didn't work (vue cli project, vue 2 + vca, no `@vue/runtime-dom` installed, `skipLibCheck` set to `false`)

I'll try later to make a github reproduction

**Comment by victorgarciaesgi** [comment]
Seems like it's not installing it, I think I will have to put it in dependencies

**Comment by victorgarciaesgi** [comment]
Can you try `0.3.7`, I removed `@vue/runtime-dom` dependency, and just added `csstypes` instead! So now it should only depend on it

**Comment by jacekkarczmarczyk** [comment]
It works with 0.3.7, thank you!
